import type { Metadata } from "next";
import { AppProvider } from "@/contexts/AppContext";
import { Providers } from "./providers";
import "./globals.css";
import { Montserrat, Inter, Roboto } from "next/font/google";

export const metadata: Metadata = {
	title: "Cubos Movies",
	description: "Generated by create next app"
};

const montserrat = Montserrat({
	subsets: ["latin"],
	variable: "--font-montserrat"
});

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter"
});

const roboto = Roboto({
	subsets: ["latin"],
	variable: "--font-roboto",
	weight: ["100", "300", "400", "500", "700", "900"]
});

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="pt-br"
			className={`${montserrat.variable} ${inter.variable} ${roboto.variable}`}
		>
			<body>
				<Providers>
					<AppProvider>{children}</AppProvider>
				</Providers>
			</body>
		</html>
	);
}
